version: "3"
services:
  reverse-proxy:
    # The official v2.0 Traefik docker image
    image: traefik:v2.10.1
    restart: unless-stopped
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=true
      - --providers.file.directory=/etc/traefik/dynamic
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
    ports:
      # Expose 81 since Windows System process is using 80 ¯\_(ツ)_/¯
      - 80:80
      # Expose 443 for TLS
      - 443:443
      # The Web UI (enabled by --api.insecure=true)
      - 8080:8080
      # For Docker registy
      - 5000:5000
    volumes:
      # Allows Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount the dynamic configuration
      - ./traefik/certs-traefik.yaml:/etc/traefik/dynamic/certs-traefik.yaml
      # Mount the directory containing the certs
      - ./traefik/certs:/etc/certs/
    networks:
      - nexus_net


  nexus:
    image: sonatype/nexus3
    restart: unless-stopped
    hostname: ${HOSTNAME}
    container_name: nexus
    volumes:
      - ./nexus-data:/nexus-data
    networks:
      - nexus_net
    labels:
      # - traefik.port=8081
      - traefik.http.routers.nexus.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.nexus.tls=true
      # - traefik.http.routers.nexus.tls.certresolver=myresolver
      - traefik.http.routers.nexus.service=nexus
      - traefik.http.services.nexus.loadBalancer.server.port=8081

      - traefik.http.routers.registy.rule=Host(`${DOCKRE_REGISTY}`)
      - traefik.http.routers.registy.tls=true
      - traefik.http.routers.registy.service=registy
      - traefik.http.services.registy.loadBalancer.server.port=5000

        #- traefik.enable=true
        #- traefik.http.routers.nexus.entrypoints=websecure
        #- traefik.http.routers.nexus.tls=true

networks:
  nexus_net:
    driver: bridge