version: '3.5'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: gitlab.danilasm.com
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        external_url 'https://gitlab.danilasm.com:443'
    ports:
      - "443:443"
      - "80:80"
      - "2222:22"
    volumes:
      - /srv/gitlab/config:/etc/gitlab
      - /srv/gitlab/data:/var/opt/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
    networks:
      - gitlab_net

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    depends_on:
      - gitlab
    volumes:
      - /srv/gitlab/gitlab-runner/data:/home/gitlab_ci_multi_runner/data
      - /srv/gitlab/gitlab-runner/config:/etc/gitlab-runner
      - /srv/gitlab/var/run/docker.sock:/var/run/docker.sock
    environment:
      - CI_SERVER_URL=https://gitlab.danilasm.com/ci
    networks:
      - gitlab_net

networks:
  gitlab_net:
