version: '3.8'
services:
  db:
    image: postgres:bullseye
    container_name: db
    environment:
      POSTGRES_PASSWORD: qw12er34
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /srv/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"