version: '3'
services:
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    volumes:
     - "./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro"
     - "./nginx-conf/danil-gitlab.conf:/etc/nginx/conf.d/gitlab.conf:ro"
     - "./nginx-logs:/var/log/nginx"
     - "./nginx-certs:/etc/nginx/certs:ro"
    network_mode: "bridge"
    ports:
     - "80:80"
     - "443:443"
    depends_on:
      - gitlab_app
    links:
      - gitlab_app

  gitlab_app:
    restart: always
    image: 'gitlab/gitlab-—Åe:latest'
    hostname: 'git'
    container_name: gitlab_app
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.danilasm.com'
        nginx['enable'] = false
        postgresql['enable'] = false
        redis['enable'] = false
        gitlab_rails['db_database'] = "danil_gitlab_production"
        web_server['external_users'] = ['www-data']
        gitlab_rails['db_adapter'] = "postgresql"
        gitlab_rails['db_username'] = "gitlab"
        gitlab_rails['db_password'] = "***********"
        gitlab_rails['db_host'] = "postgresql"
        gitlab_rails['db_port'] = 5432
        gitlab_rails['redis_host'] = "redis"
        gitlab_rails['redis_port'] = 6379
        gitlab_rails['redis_database'] = 0
        gitlab_workhorse['enable'] = true
        gitlab_workhorse['listen_network'] = "tcp"
        gitlab_workhorse['listen_addr'] = "0.0.0.0:8081"
        gitlab_workhorse['auth_backend'] = "http://localhost:8080"
    expose:
    - "8081"
    volumes:
     - "./gitlab-config:/etc/gitlab"
     - "./gitlab-data:/var/opt/gitlab"
     - "./gitlab-logs:/var/log/gitlab"
     - "./license_key.pub:/opt/gitlab/embedded/service/gitlab-rails/.license_encryption_key.pub"
    network_mode: "bridge"
    ports:
     - "2222:22"
    depends_on:
      - postgresql
      - redis
    links:
      - postgresql
      - redis

  postgresql:
    restart: always
    image: postgres:13
    container_name: postgresql
    environment:
     - POSTGRES_USER=gitlab
     - POSTGRES_PASSWORD=*********
     - POSTGRES_DB=danil_gitlab_production
     - POSTGRES_EXTENSION=pg_trgm
    expose:
    - "5432"
    volumes:
     - "./postgresql-data:/var/lib/postgresql/data"
    network_mode: "bridge"

  redis:
    restart: always
    image: redis:latest
    container_name: redis
    expose:
    - "6379"
    volumes:
     - "./redis-data:/data"
    network_mode: "bridge"

  gitlab-runner:
    image: 'gitlab/gitlab-runner:latest'
    container_name: gitlab-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gitlab-runner/config:/etc/gitlab-runner
      - ./gitlab-runner/data:/home/gitlab_ci_multi_runner/data
    environment:
      - CI_SERVER_URL=https://gitlab.danilasm.com/ci
    restart: always
