stages:
  - nginx
  - site.ru


nginx:
  stage: nginx
  variables:
    CONTAINERNAME: 'nginx'
    SITE: 'site.ru'
  script:
    - docker ps -a -q --filter "name=${CONTAINERNAME}" | grep -q . && docker rm -f ${CONTAINERNAME} || true
    - |
        docker run -d \
          --name="${CONTAINERNAME}" \
          --restart=unless-stopped \
          --net=host \
          -v $(pwd)/nginx/conf.d:/etc/nginx/conf.d \
          -v $(pwd)/nginx/ssl/${SITE}:/etc/nginx/ssl/${SITE} \
          -v /srv/${SITE}:/srv/${SITE} \
          ${CONTAINERNAME}
  only:
    - main
  tags:
    - shell
  when: manual


.job_definition: &node_builder
  script:
    - cd /srv/${CONTAINERNAME}
    - eval "$(ssh-agent -s)" && ssh-add ~/.ssh/${CONTAINERNAME}
    - git pull
    - |
        docker run --rm \
          --name="${CONTAINERNAME}" \
          -w /app \
          -v /srv/${CONTAINERNAME}:/app \
          node:${NODE_VERSION} \
              sh -c "npm cache clean --force && npm install && npm run build"

build:
  stage: site.ru
  variables:
    CONTAINERNAME: 'site.ru'
    NODE_VERSION: '18.18.0'
  <<: *node_builder
  script:
  only:
    - main
  tags:
    - shell
  when: always
