version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: unless-stopped
    container_name: jenkins
    ports:
      - "8080:8080"
      - "443:8443"
      - "50000:50000"
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
      - ./jenkins/ssl:/var/jenkins_home/keystore
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      sh -c "java -Dhudson.model.DirectoryBrowserSupport.CSP=\"\" -jar /usr/share/jenkins/jenkins.war --httpPort=-1 --httpsPort=8443 --httpsKeyStore=/var/jenkins_home/keystore/jenkinsserver.jks --httpsKeyStorePassword=jenkins"

  # haproxy:
    # image: haproxy:latest
    # restart: unless-stopped
    # container_name: haproxy
    # ports:
      # - "443:443"
    # volumes:
      # - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      # - ./ssl/haproxy.pem:/srv/haproxy.pem